<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VKAG1RPA" failures="2" tests="17" name="Class" time="99.824" errors="0" timestamp="2021-02-05T11:26:14 IST">
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="selectALL_forClassCode" time="3.453"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="createClassCode" time="3.569"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="createClassCode" time="1.125"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="createClassCode" time="1.363"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="createClassCode" time="1.398"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="saveClassCode" time="25.495">
    <failure type="java.lang.AssertionError" message="No Error Message validation for save action expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No Error Message validation for save action expected [true] but found [false]
at com.extraPOSTest.testCases.inventory.maintenance.TC_Class.saveClassCode(TC_Class.java:286)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- saveClassCode -->
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="addTwoSameClassCode" time="1.972"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="addTwoSameClassCode" time="0.964"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="saveTwoCategoryCode" time="5.067"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="searchClassPage" time="3.557"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="searchClassPage" time="3.362"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="searchClassPage" time="3.365"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="searchClassPage" time="4.133"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="checkReverseOrderValidation_ClassCode" time="2.049"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="checkReverseOrderValidation_ClassCode" time="0.616"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="checkReverseOrderValidation_ClassCode" time="0.276"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Class" name="checkReverseOrderValidation_ClassCode" time="21.277">
    <failure type="java.lang.AssertionError" message="No validation for duplicate Classcode expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No validation for duplicate Classcode expected [true] but found [false]
at com.extraPOSTest.testCases.inventory.maintenance.TC_Class.checkReverseOrderValidation_ClassCode(TC_Class.java:838)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkReverseOrderValidation_ClassCode -->
</testsuite> <!-- Class -->
