<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VKAG1RPA" failures="1" tests="9" name="LOV" time="63.581" errors="0" timestamp="2021-02-05T13:09:22 IST">
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_LOV" name="selectALL_forLOVCode" time="4.687"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_LOV" name="createLOVCode" time="2.043"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_LOV" name="createLOVCode" time="1.741"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_LOV" name="createLOVCode" time="1.749"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_LOV" name="createLOVCode" time="2.071"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_LOV" name="addLOVrow" time="1.15"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_LOV" name="addLOVrow" time="6.142"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_LOV" name="addLOVrow" time="4.007"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_LOV" name="addLOVrow" time="24.415">
    <failure type="java.lang.AssertionError" message="There is NO proper validation for the duplicate lov Row Code expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: There is NO proper validation for the duplicate lov Row Code expected [true] but found [false]
at com.extraPOSTest.testCases.inventory.maintenance.TC_LOV.addLOVrow(TC_LOV.java:528)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- addLOVrow -->
</testsuite> <!-- LOV -->
