<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VKAG1RPA" failures="2" tests="18" name="SubCategory" time="111.905" errors="0" timestamp="2021-02-05T11:22:43 IST">
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="selectALL_forSubCategoryCode" time="3.957"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="createSubCategoryCode" time="5.09"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="createSubCategoryCode" time="3.799"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="createSubCategoryCode" time="2.996"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="createSubCategoryCode" time="2.063"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="createSubCategoryCode" time="1.683"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="saveSubCategoryCode" time="25.206">
    <failure type="java.lang.AssertionError" message="No Error Message validation for save action expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No Error Message validation for save action expected [true] but found [false]
at com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory.saveSubCategoryCode(TC_SubCategory.java:340)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- saveSubCategoryCode -->
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="addTwoSameSubCategoryCode" time="1.859"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="addTwoSameSubCategoryCode" time="0.714"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="saveTwoSubCategoryCode" time="5.305"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="searchCategoryPage" time="4.414"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="searchCategoryPage" time="4.429"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="searchCategoryPage" time="4.58"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="searchCategoryPage" time="5.119"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="checkReverseOrderValidation_SubCategoryCode" time="2.296"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="checkReverseOrderValidation_SubCategoryCode" time="0.562"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="checkReverseOrderValidation_SubCategoryCode" time="0.279"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="checkReverseOrderValidation_SubCategoryCode" time="21.472">
    <failure type="java.lang.AssertionError" message="No validation for duplicate Subcatcode expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No validation for duplicate Subcatcode expected [true] but found [false]
at com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory.checkReverseOrderValidation_SubCategoryCode(TC_SubCategory.java:893)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkReverseOrderValidation_SubCategoryCode -->
</testsuite> <!-- SubCategory -->
