<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-VKAG1RPA" failures="2" tests="16" name="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" time="81.168" errors="0" timestamp="2021-02-05T11:30:33 IST" skipped="0">
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="selectALL_forTypeCode" time="4.180"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="createTypeCode" time="0.960"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="createTypeCode" time="3.626"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="createTypeCode" time="1.265"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="saveTypeCode" time="24.894">
    <failure message="No Error Message validation for save action expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Error Message validation for save action expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.extraPOSTest.testCases.inventory.maintenance.TC_Type.saveTypeCode(TC_Type.java:282)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- saveTypeCode -->
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="addTwoSameTypeCode" time="1.667"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="addTwoSameTypeCode" time="0.783"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="saveTwoTypeCode" time="5.146"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="searchTypePage" time="3.444"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="searchTypePage" time="3.297"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="searchTypePage" time="4.077"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="searchTypePage" time="3.524"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="checkReverseOrderValidation_TypeCode" time="0.576"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="checkReverseOrderValidation_TypeCode" time="0.308"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="checkReverseOrderValidation_TypeCode" time="21.374">
    <failure message="No validation for duplicate Typecode expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No validation for duplicate Typecode expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.extraPOSTest.testCases.inventory.maintenance.TC_Type.checkReverseOrderValidation_TypeCode(TC_Type.java:818)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkReverseOrderValidation_TypeCode -->
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Type" name="checkReverseOrderValidation_TypeCode" time="2.047"/>
  <system-out/>
</testsuite> <!-- com.extraPOSTest.testCases.inventory.maintenance.TC_Type -->
